### ISSUE TITLE
Code generation technique

### ISSUE THREAD

**Issue by Scooletz** [NethermindEth/IL-EVM#1]
The modern approaches that can be used for dynamic code generation include:

1. IL generation, for example:
   1. [Sigil](https://github.com/kevin-montrose/Sigil)
   2. [.NET IL Generator](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.emit.ilgenerator)
   3. [Fody](https://github.com/Fody/Fody)
1. Source Generators (see: [page](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview))
1. CodeCom

A design decision is required to select one to use in the project

**Comment by LukaszRozmej** [comment]
Make it pluggable and later benchmark!

**Comment by Demuirgos** [comment]
ig IL emitter would be more useful in this case, because source generators will require the presence of most needed data (smart contract code in this case at compile time), so imo what we need is a framework that can emil IL on the fly.

**Comment by Scooletz** [comment]
If we make it JIT, I'd say going with the first is the way to go. If we do a prebuild, I'd say the latter. Also, nothing prohibits us from using Sigil or similar to build. It'd make it easier to manage and less error prone. There are some great examples out there https://github.com/protobuf-net/protobuf-net/blob/fba0624ffeafb14b6ef7a713b950f62fd74c34e1/src/protobuf-net/Compiler/CompilerContext.cs . If this is it, I'd say let's go with IL + helper methods whenever possible.

**Comment by Scooletz** [comment]
**IL**

We agreed that IL level is the way to go now. With some helpers, like either shared methods or higher level tooling with Sigil it should be easy to express. Also, it makes it much more portable with client-side generation.
