### ISSUE TITLE
LOG

### ISSUE THREAD

**Issue by Scooletz** [NethermindEth/IL-EVM#16]

**Comment by SiddharthV1** [comment]
PR for this : https://github.com/NethermindEth/nethermind/pull/7290

**Comment by Scooletz** [comment]
PR is merged. Is this done @SiddharthV1 @Demuirgos ?

**Comment by Demuirgos** [comment]
> PR is merged. Is this done @SiddharthV1 @Demuirgos ?

I merged it

**Comment by SiddharthV1** [comment]
> PR is merged. Is this done @SiddharthV1 @Demuirgos ?

yes done..but there were some improvements suggested by @Demuirgos that I wanted address  at some point
