### ISSUE TITLE
When to precompile

### ISSUE THREAD

**Issue by Scooletz** [NethermindEth/IL-EVM#3]
The contract can be precompiled:

1. just in time on the client-side 
2. precompile during Nethermind client build and shipped with Nethermind

**Comment by LukaszRozmej** [comment]
If just-in-time the precompilation should always be in the background, for example in-between blocks, not affecting main block verification time.

**Comment by Scooletz** [comment]
I think we should test and measure. The tool should be agnostic and if it's run during the build, the only different is that the output is persistent and is a dll with precompiled chunks of code. When running on the client, we could either persist or do it in the runtime after breaching some metric of the execution of a given one.

**Comment by Scooletz** [comment]
**Nethermind build**

Shipping with Nethermind should consider gathering data per network and load the network aware context. Even with some similarities the stats can be different.

As we ship often, we can use that as opportunity to ship often.
