### ISSUE TITLE
What to precompile

### ISSUE THREAD

**Issue by Scooletz** [NethermindEth/IL-EVM#4]
An algorithm for selecting what to precompile should be selected.

**Comment by Demuirgos** [comment]
can we use the Metrics API to collect data about what smart contracts are called and if some one crossed a certain threshold we analyze/emit a precompiled version of it and cache it around?

**Comment by Scooletz** [comment]
I think I like idea of finding the longest chunks that are executed. It could be that we have a Nethermind client being run with EVM augmented. Whether shipped to client or just used for test runs with our nodes, we could do it in a similar way

It could be done in a really easy way, we could gather `PC` for the given `codeHash` and collect the number until some special operation happens (CALL, SSTORE, SLOAD, JUMP, etc.). This, would create a simple entry for a `codeHash` -> PC -> time-or-length

With that we we could run IL-EVM for the contract once it's found to be useful but first of all, we can use it for us to see the numbers and think of the optimizations!

**Comment by Scooletz** [comment]
Let's dive into one more solution mode. The `chunks` can be identified across contracts with non-cryptographic hashes (XX64 should be just enough) so that we gather information about a given chunk in a context of the contract but we notice and collect it in a way that allows to notice the same chunks of code repeated across many contracts. This, it requires a confirmation, could be useful for #9 and similar where the higher level language construct is transformed into the same bytecodes.

**Comment by Scooletz** [comment]
As in #3 we decided that it will be done during build, we can run some stats on nodes hosted by us to gather data.

Open a question how to find similarities. The proposal from the above, does not include the constants extraction (which can be easily done). 

Having a fast full sync is important for gathering data and reanalyze data especially when we change the algorithm for finding it. Without changes, it's only the last blocks that should have this analyzes run.

Consider a walking window for a full sync / archive sync
.
