### ISSUE TITLE
Interactions with other contracts

### ISSUE THREAD

**Issue by Scooletz** [NethermindEth/IL-EVM#5]
The way of interacting with other contracts should be selected. This should cover both directions:

1. `jitted` -> `regular`
2. `regular` -> `jitted`

If due to other decisions, some of the above are not possible, make it explicit.

**Comment by LukaszRozmej** [comment]
Would be good to make those interactions as low cost as possible.

**Comment by Scooletz** [comment]
I'd leave it as is, meaning that the call is the same, but... we could precompile the whole contract being called if we can be that smart! For example, let's say it's a delegate to a `SafeMath` or whatever other library that we can make it precompiled, then, we could be much much faster with executing it.

**Comment by Demuirgos** [comment]
wouldn't calling from regular to precompile behave like calling a precompile?, the other way around has the context switching in the call sight that might be a bit more complex to deal with

**Comment by Scooletz** [comment]
I'm not 100% if I understand the regular->precompile fully and AFAIK (which might be wrong) is that the call site management is different? We can dive into this during a call and have it sorted out what we'll cover and in which way.

**Comment by Demuirgos** [comment]
regular to precompile as far as I know, is just simple CALL opcode (or one other variant of it), with the address of the precompile as an argument, pretty simple, so from regular to a IL precompiled contract it's gonna be straight forward, the inverse as we said in the previous call will be tricky

**Comment by LukaszRozmej** [comment]
> regular to precompile as far as I know, is just simple CALL opcode (or one other variant of it), with the address of the precompile as an argument, pretty simple, so from regular to a IL precompiled contract it's gonna be straight forward, the inverse as we said in the previous call will be tricky

only if datastructures are compatible, no idea how compiled contracts would access memory or stack - I expect them to use .Net stack rather than `EvmStack` for example.

**Comment by Scooletz** [comment]
We leave them as is, leaving the optimization opportunities to #6 and similar.
