### ISSUE TITLE
Sandboxing

### ISSUE THREAD

**Issue by Scooletz** [NethermindEth/IL-EVM#7]
How to ensure that the precompiled contract cannot escape the sanbox

**Comment by LukaszRozmej** [comment]
Could you provide an example how it could escape it?
Generally contract should have only access to some objects that were passed + it is own created ones.
I expect proper .net level sandboxing will have too big performance penalty and defeat main point of the speedup.
Worst case scenario - use only pre-compiled ones that are somehow verified.

**Comment by Scooletz** [comment]
I don't have any. Just captured what was stated before. @benaadams could you chime in?

**Comment by Scooletz** [comment]
Look for source code analyzers for `Unsafe` family. Maybe there are some in dotnet repo?

**Comment by benaadams** [comment]
> Could you provide an example how it could escape it? 

1. Bugs in implementation
2. Evm opcodes `JUMP`/`JUMPI` using data as destination

In the current interpreted world if the `pc` goes out of bounds then it throws an `IndexOutOfRangeException` when trying to get the next instruction from the code Span. With complied code it will just execute whatever assembly is there and keep running (e.g. Nethermind exe code)

It is slightly mitigated by the destination of any jump needing to be a `JUMPDEST`.

> Generally contract should have only access to some objects that were passed + it is own created ones.

You are thinking of more of a post-EOF world; where the evm itself is more locked down and contracts are verified.

Is more a consideration to be very aware of in the implementation

**Comment by Scooletz** [comment]
If we assume no `JMP` for the initial IL-EVM, so linear PC increments, and a clear pop/push stack behavior, do you see anything at this point @benaadams ? I'm not trying invalidate the argument but rather clarify it for the first phase.

**Comment by benaadams** [comment]
> If we assume no JMP for the initial IL-EVM

I think you will have trouble finding contracts as that will mean no `if` or `for` statements? (Possibly no methods either, as contracts start with a lookup of the called method then jump to it)

However, to your question, that's the main dangerous area (and the matching of `JUMPDEST` does provide some safety)

**Comment by Scooletz** [comment]
Let me clarify. I'm discussing chunks of opcodes, not whole scenarios as we agreed in #2 to go with partial first, then expand.
